version: '3.9'

services:
  nestapp:
    container_name: nestapp2
    image: nestapp2:1.0.0
    build: .
    ports:
      - 3001:3001
    environment:
      - REDIS_HOST=host.docker.internal 
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis2
    volumes:
      - pgdata:/var/lib/redis/data
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=host.docker.internal
volumes:
  pgdata: {}